apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      maxLines: 1000
    secureJsonData:
      httpHeaderValue1: fake

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
