server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    # If your Loki ever enables multi-tenancy, uncomment the header below.
    # headers:
    #   X-Scope-OrgID: sre-lab

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    # Derive useful labels from Docker metadata
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        regex: '/(.*)'
        replacement: '$1'

      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream

      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service

      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project

    # ✅ THIS was the problem — it belongs under the scrape_config
    pipeline_stages:
      - docker: {}

