global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "app"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "sre-lab-app:8080"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

